# ────────── Project identification ──────────
sonar.projectKey=chdelucia_petsch
sonar.organization=chdelucia
sonar.projectName=petsch
sonar.projectVersion=1.0

sonar.sources=apps,libs
sonar.sourceEncoding=UTF-8
sonar.tests=apps,libs
sonar.test.inclusions=**/*.spec.ts

sonar.exclusions=\
**/node_modules/**,\
**/.vscode/**,\
**/dist/**,\
**/*.config.ts,\
**/main.ts,\
**/*routes.ts,\
**/*test-setup.ts,\
**/*.const.ts,\
libs/shared/util/**,\
libs/shared/ui/**,\
**/**.config.mts,\

sonar.coverage.exclusions=\
**/*.stories.ts,\
**/*.interface.ts,\
**/*.model.ts,\
libs/shared/util/**,\
libs/shared/ui/**,\
**/petshop-e2e/**,\

sonar.typescript.lcov.reportPaths=coverage/petshop/lcov.info,coverage/libs/**/lcov.info
